const coinOptions = [
  {key: 'Choose...', text: 'Choose...', value: 'CUSTOM'},
  {key: 'ZRX', text: '0x', value: 'ZRX'},
  {key: 'ATM', text: 'ATMChain', value: 'ATM'},
  {key: 'ACT', text: 'Achain', value: 'ACT'},
  {key: 'ADX', text: 'AdEx', value: 'ADX'},
  {key: 'ADT', text: 'adToken', value: 'ADT'},
  {key: 'ELF', text: 'aelf', value: 'ELF'},
  {key: 'AEON', text: 'Aeon', value: 'AEON'},
  {key: 'AE', text: 'Aeternity', value: 'AE'},
  {key: 'AGRS', text: 'Agoras Tokens', value: 'AGRS'},
  {key: 'DLT', text: 'Agrello', value: 'DLT'},
  {key: 'AION', text: 'Aion', value: 'AION'},
  {key: 'AST', text: 'AirSwap', value: 'AST'},
  {key: 'SOC', text: 'All Sports', value: 'SOC'},
  {key: 'AMB', text: 'Ambrosus', value: 'AMB'},
  {key: 'APPC', text: 'AppCoins', value: 'APPC'},
  {key: 'ANT', text: 'Aragon', value: 'ANT'},
  {key: 'ARDR', text: 'Ardor', value: 'ARDR'},
  {key: 'ARK', text: 'Ark', value: 'ARK'},
  {key: 'XAS', text: 'Asch', value: 'XAS'},
  {key: 'REP', text: 'Augur', value: 'REP'},
  {key: 'VEE', text: 'BLOCKv', value: 'VEE'},
  {key: 'BNT', text: 'Bancor', value: 'BNT'},
  {key: 'BAT', text: 'Basic Attention Token', value: 'BAT'},
  {key: 'BIX', text: 'Bibox Token', value: 'BIX'},
  {key: 'BNB', text: 'Binance Coin', value: 'BNB'},
  {key: 'BAY', text: 'BitBay', value: 'BAY'},
  {key: 'CAT', text: 'BitClave', value: 'CAT'},
  {key: 'BDG', text: 'BitDegree', value: 'BDG'},
  {key: 'BTS', text: 'BitShares', value: 'BTS'},
  {key: 'BTC', text: 'Bitcoin', value: 'BTC'},
  {key: 'BCH', text: 'Bitcoin Cash', value: 'BCH'},
  {key: 'BTG', text: 'Bitcoin Gold', value: 'BTG'},
  {key: 'BTCD', text: 'BitcoinDark', value: 'BTCD'},
  {key: 'BTX', text: 'Bitcore', value: 'BTX'},
  {key: 'BLOCK', text: 'Blocknet', value: 'BLOCK'},
  {key: 'TIX', text: 'Blocktix', value: 'TIX'},
  {key: 'BLT', text: 'Bloom', value: 'BLT'},
  {key: 'BLZ', text: 'Bluzelle', value: 'BLZ'},
  {key: 'BRD', text: 'Bread', value: 'BRD'},
  {key: 'BCO', text: 'BridgeCoin', value: 'BCO'},
  {key: 'BURST', text: 'Burst', value: 'BURST'},
  {key: 'GBYTE', text: 'Byteball Bytes', value: 'GBYTE'},
  {key: 'BCN', text: 'Bytecoin', value: 'BCN'},
  {key: 'BITCNY', text: 'bitCNY', value: 'BITCNY'},
  {key: 'BTM', text: 'Bytom', value: 'BTM'},
  {key: 'CV', text: 'carVertical', value: 'CV'},
  {key: 'COSS', text: 'COSS', value: 'COSS'},
  {key: 'C20', text: 'CRYPTO20', value: 'C20'},
  {key: 'CAPP', text: 'Cappasity', value: 'CAPP'},
  {key: 'ADA', text: 'Cardano', value: 'ADA'},
  {key: 'CTR', text: 'Centra', value: 'CTR'},
  {key: 'LINK', text: 'ChainLink', value: 'LINK'},
  {key: 'CND', text: 'Cindicator', value: 'CND'},
  {key: 'CVC', text: 'Civic', value: 'CVC'},
  {key: 'CLOAK', text: 'CloakCoin', value: 'CLOAK'},
  {key: 'COB', text: 'Cobinhood', value: 'COB'},
  {key: 'CFI', text: 'Cofound.it', value: 'CFI'},
  {key: 'CDT', text: 'CoinDash', value: 'CDT'},
  {key: 'COLX', text: 'ColossusCoinXT', value: 'COLX'},
  {key: 'XCP', text: 'Counterparty', value: 'XCP'},
  {key: 'CRW', text: 'Crown', value: 'CRW'},
  {key: 'CNX', text: 'Cryptonex', value: 'CNX'},
  {key: 'CMT', text: 'CyberMiles', value: 'CMT'},
  {key: 'DCT', text: 'DECENT', value: 'DCT'},
  {key: 'DEW', text: 'DEW', value: 'DEW'},
  {key: 'DASH', text: 'Dash', value: 'DASH'},
  {key: 'DAT', text: 'Datum', value: 'DAT'},
  {key: 'MANA', text: 'Decentraland', value: 'MANA'},
  {key: 'HST', text: 'Decision Token', value: 'HST'},
  {key: 'DCR', text: 'Decred', value: 'DCR'},
  {key: 'DBC', text: 'DeepBrain Chain', value: 'DBC'},
  {key: 'ONION', text: 'DeepOnion', value: 'ONION'},
  {key: 'DPY', text: 'Delphy', value: 'DPY'},
  {key: 'DENT', text: 'Dent', value: 'DENT'},
  {key: 'DCN', text: 'Dentacoin', value: 'DCN'},
  {key: 'DMD', text: 'Diamond', value: 'DMD'},
  {key: 'DGB', text: 'DigiByte', value: 'DGB'},
  {key: 'XDN', text: 'DigitalNote', value: 'XDN'},
  {key: 'DGD', text: 'DigixDAO', value: 'DGD'},
  {key: 'DIME', text: 'Dimecoin', value: 'DIME'},
  {key: 'DNT', text: 'district0x', value: 'DNT'},
  {key: 'DOGE', text: 'Dogecoin', value: 'DOGE'},
  {key: 'DRGN', text: 'Dragonchain', value: 'DRGN'},
  {key: 'DTR', text: 'Dynamic Trading Rights', value: 'DTR'},
  {key: 'ECN', text: 'E-coin', value: 'ECN'},
  {key: 'ECC', text: 'ECC', value: 'ECC'},
  {key: 'EOS', text: 'EOS', value: 'EOS'},
  {key: 'LEND', text: 'ETHLend', value: 'LEND'},
  {key: 'EDG', text: 'Edgeless', value: 'EDG'},
  {key: 'EDO', text: 'Eidoo', value: 'EDO'},
  {key: 'EMC2', text: 'Einsteinium', value: 'EMC2'},
  {key: 'ECA', text: 'Electra', value: 'ECA'},
  {key: 'ETN', text: 'Electroneum', value: 'ETN'},
  {key: 'EMC', text: 'Emercoin', value: 'EMC'},
  {key: 'TSL', text: 'Energo', value: 'TSL'},
  {key: 'ENG', text: 'Enigma', value: 'ENG'},
  {key: 'ENJ', text: 'Enjin Coin', value: 'ENJ'},
  {key: 'ETH', text: 'Ethereum', value: 'ETH'},
  {key: 'ETC', text: 'Ethereum Classic', value: 'ETC'},
  {key: 'FUEL', text: 'Etherparty', value: 'FUEL'},
  {key: 'ETHOS', text: 'Ethos', value: 'ETHOS'},
  {key: 'EVX', text: 'Everex', value: 'EVX'},
  {key: 'XP', text: 'Experience Points', value: 'XP'},
  {key: 'FCT', text: 'Factom', value: 'FCT'},
  {key: 'FAIR', text: 'FairCoin', value: 'FAIR'},
  {key: 'FTC', text: 'Feathercoin', value: 'FTC'},
  {key: '1ST', text: 'FirstBlood', value: '1ST'},
  {key: 'FLASH', text: 'Flash', value: 'FLASH'},
  {key: 'FUN', text: 'FunFair', value: 'FUN'},
  {key: 'GXS', text: 'GXShares', value: 'GXS'},
  {key: 'GAME', text: 'GameCredits', value: 'GAME'},
  {key: 'GAS', text: 'Gas', value: 'GAS'},
  {key: 'GVT', text: 'Genesis Vision', value: 'GVT'},
  {key: 'GTO', text: 'Gifto', value: 'GTO'},
  {key: 'GNO', text: 'Gnosis', value: 'GNO'},
  {key: 'GNT', text: 'Golem', value: 'GNT'},
  {key: 'GRS', text: 'Groestlcoin', value: 'GRS'},
  {key: 'NLG', text: 'Gulden', value: 'NLG'},
  {key: 'HTML', text: 'HTMLCOIN', value: 'HTML'},
  {key: 'THC', text: 'HempCoin', value: 'THC'},
  {key: 'HPB', text: 'High Performance Blockchain', value: 'HPB'},
  {key: 'HVN', text: 'Hive', value: 'HVN'},
  {key: 'HSR', text: 'Hshare', value: 'HSR'},
  {key: 'HMQ', text: 'Humaniq', value: 'HMQ'},
  {key: 'IOC', text: 'I/O Coin', value: 'IOC'},
  {key: 'ICX', text: 'ICON', value: 'ICX'},
  {key: 'RLC', text: 'iExec RLC', value: 'RLC'},
  {key: 'IDH', text: 'indaHash', value: 'IDH'},  
  {key: 'INS', text: 'INS Ecosystem', value: 'INS'},
  {key: 'ION', text: 'ION', value: 'ION'},
  {key: 'IOST', text: 'IOStoken', value: 'IOST'},
  {key: 'MIOTA', text: 'IOTA', value: 'MIOTA'},
  {key: 'ICN', text: 'Iconomi', value: 'ICN'},
  {key: 'IGNIS', text: 'Ignis', value: 'IGNIS'},
  {key: 'INK', text: 'Ink', value: 'INK'},
  {key: 'IPL', text: 'InsurePal', value: 'IPL'},
  {key: 'INT', text: 'Internet Node Token', value: 'INT'},
  {key: 'ITC', text: 'IoT Chain', value: 'ITC'},
  {key: 'IXT', text: 'iXledger', value: 'IXT'},
  {key: 'KRM', text: 'Karma', value: 'KRM'},
  {key: 'KIN', text: 'Kin', value: 'KIN'},
  {key: 'KMD', text: 'Komodo', value: 'KMD'},
  {key: 'KCS', text: 'KuCoin Shares', value: 'KCS'},
  {key: 'KNC', text: 'Kyber Network', value: 'KNC'},
  {key: 'LA', text: 'LAToken', value: 'LA'},
  {key: 'LBC', text: 'LBRY Credits', value: 'LBC'},
  {key: 'LEO', text: 'LEOcoin', value: 'LEO'},
  {key: 'TAU', text: 'Lamden', value: 'TAU'},
  {key: 'LSK', text: 'Lisk', value: 'LSK'},
  {key: 'LTC', text: 'Litecoin', value: 'LTC'},
  {key: 'LRC', text: 'Loopring', value: 'LRC'},
  {key: 'LUN', text: 'Lunyr', value: 'LUN'},
  {key: 'LKK', text: 'Lykke', value: 'LKK'},
  {key: 'ART', text: 'Maecenas', value: 'ART'},
  {key: 'MAID', text: 'MaidSafeCoin', value: 'MAID'},
  {key: 'MKR', text: 'Maker', value: 'MKR'},
  {key: 'GUP', text: 'Matchpool', value: 'GUP'},
  {key: 'MED', text: 'MediBloc', value: 'MED'},
  {key: 'MDS', text: 'MediShares', value: 'MDS'},
  {key: 'MLN', text: 'Melon', value: 'MLN'},
  {key: 'MER', text: 'Mercury', value: 'MER'},
  {key: 'MTL', text: 'Metal', value: 'MTL'},
  {key: 'ETP', text: 'Metaverse ETP', value: 'ETP'},
  {key: 'MNX', text: 'MinexCoin', value: 'MNX'},
  {key: 'MGO', text: 'MobileGo', value: 'MGO'},
  {key: 'MOD', text: 'Modum', value: 'MOD'},
  {key: 'MDA', text: 'Moeda Loyalty Points', value: 'MDA'},
  {key: 'MONA', text: 'MonaCoin', value: 'MONA'},
  {key: 'MCO', text: 'Monaco', value: 'MCO'},
  {key: 'XMR', text: 'Monero', value: 'XMR'},
  {key: 'MTH', text: 'Monetha', value: 'MTH'},
  {key: 'MOON', text: 'Mooncoin', value: 'MOON'},
  {key: 'NGC', text: 'NAGA', value: 'NGC'},
  {key: 'NAV', text: 'NAV Coin', value: 'NAV'},
  {key: 'XEM', text: 'NEM', value: 'XEM'},
  {key: 'NEO', text: 'NEO', value: 'NEO'},
  {key: 'NMC', text: 'Namecoin', value: 'NMC'},
  {key: 'XRB', text: 'Nano', value: 'XRB'},
  {key: 'NEBL', text: 'Neblio', value: 'NEBL'},
  {key: 'NAS', text: 'Nebulas', value: 'NAS'},
  {key: 'NXS', text: 'Nexus', value: 'NXS'},
  {key: 'NET', text: 'Nimiq', value: 'NET'},
  {key: 'NLC2', text: 'NoLimitCoin', value: 'NLC2'},
  {key: 'NULS', text: 'Nuls', value: 'NULS'},
  {key: 'NXT', text: 'Nxt', value: 'NXT'},
  {key: 'OCN', text: 'Odyssey', value: 'OCN'},
  {key: 'MOT', text: 'Olympus Labs', value: 'MOT'},
  {key: 'OMG', text: 'OmiseGO', value: 'OMG'},
  {key: 'TRAC', text: 'OriginTrail', value: 'TRAC'},
  {key: 'ORME', text: 'Ormeus Coin', value: 'ORME'},
  {key: 'PRL', text: 'Oyster', value: 'PRL'},
  {key: 'PAC', text: 'PACcoin', value: 'PAC'},
  {key: 'PIVX', text: 'PIVX', value: 'PIVX'},
  {key: 'PART', text: 'Particl', value: 'PART'},
  {key: 'PASC', text: 'Pascal Coin', value: 'PASC'},
  {key: 'PPP', text: 'PayPie', value: 'PPP'},
  {key: 'PPC', text: 'Peercoin', value: 'PPC'},
  {key: 'PPY', text: 'Peerplays', value: 'PPY'},
  {key: 'PEPECASH', text: 'Pepe Cash', value: 'PEPECASH'},
  {key: 'PHR', text: 'Phore', value: 'PHR'},
  {key: 'PLR', text: 'Pillar', value: 'PLR'},
  {key: 'POE', text: 'Po.et', value: 'POE'},
  {key: 'POSW', text: 'PoSW Coin', value: 'POSW'},
  {key: 'PPT', text: 'Populous', value: 'PPT'},
  {key: 'POT', text: 'PotCoin', value: 'POT'},
  {key: 'POWR', text: 'Power Ledger', value: 'POWR'},
  {key: 'PRE', text: 'Presearch', value: 'PRE'},
  {key: 'PRO', text: 'Propy', value: 'PRO'},
  {key: 'PURA', text: 'Pura', value: 'PURA'},
  {key: 'QASH', text: 'QASH', value: 'QASH'},
  {key: 'QLC', text: 'QLINK', value: 'QLC'},
  {key: 'QBT', text: 'Qbao', value: 'QBT'},
  {key: 'QTUM', text: 'Qtum', value: 'QTUM'},
  {key: 'QSP', text: 'Quantstamp', value: 'QSP'},
  {key: 'QRL', text: 'Quantum Resistant Ledger', value: 'QRL'},
  {key: 'RHOC', text: 'RChain', value: 'RHOC'},
  {key: 'RDN', text: 'Raiden Network Token', value: 'RDN'},
  {key: 'RPX', text: 'Red Pulse', value: 'RPX'},
  {key: 'RDD', text: 'ReddCoin', value: 'RDD'},
  {key: 'REQ', text: 'Request Network', value: 'REQ'},
  {key: 'R', text: 'Revain', value: 'R'},
  {key: 'RCN', text: 'Ripio Credit Network', value: 'RCN'},
  {key: 'XRP', text: 'Ripple', value: 'XRP'},
  {key: 'RISE', text: 'Rise', value: 'RISE'},
  {key: 'SALT', text: 'SALT', value: 'SALT'},
  {key: 'XSH', text: 'SHIELD', value: 'XSH'},
  {key: 'SIB', text: 'SIBCoin', value: 'SIB'},
  {key: 'SRN', text: 'SIRIN LABS Token', value: 'SRN'},
  {key: 'SNM', text: 'SONM', value: 'SNM'},
  {key: 'SAFEX', text: 'Safe Exchange Coin', value: 'SAFEX'},
  {key: 'SLS', text: 'SaluS', value: 'SLS'},
  {key: 'SAN', text: 'Santiment Network Token', value: 'SAN'},
  {key: 'KEY', text: 'Selfkey', value: 'KEY'},
  {key: 'SHIFT', text: 'Shift', value: 'SHIFT'},
  {key: 'SC', text: 'Siacoin', value: 'SC'},
  {key: 'OST', text: 'Simple Token', value: 'OST'},
  {key: 'SNGLS', text: 'SingularDTV', value: 'SNGLS'},
  {key: 'AGI', text: 'SingularityNET', value: 'AGI'},
  {key: 'SKY', text: 'Skycoin', value: 'SKY'},
  {key: 'SMART', text: 'SmartCash', value: 'SMART'},
  {key: 'SPHTX', text: 'SophiaTX', value: 'SPHTX'},
  {key: 'SPANK', text: 'SpankChain', value: 'SPANK'},
  {key: 'XSPEC', text: 'Spectrecoin', value: 'XSPEC'},
  {key: 'SNT', text: 'Status', value: 'SNT'},
  {key: 'STEEM', text: 'Steem', value: 'STEEM'},
  {key: 'SBD', text: 'Steem Dollars', value: 'SBD'},
  {key: 'XLM', text: 'Stellar', value: 'XLM'},
  {key: 'STORJ', text: 'Storj', value: 'STORJ'},
  {key: 'STORM', text: 'Storm', value: 'STORM'},
  {key: 'STRAT', text: 'Stratis', value: 'STRAT'},
  {key: 'DATA', text: 'Streamr DATAcoin', value: 'DATA'},
  {key: 'SUB', text: 'Substratum', value: 'SUB'},
  {key: 'SNC', text: 'SunContract', value: 'SNC'},
  {key: 'UNITY', text: 'SuperNET', value: 'UNITY'},
  {key: 'SWFTC', text: 'SwftCoin', value: 'SWFTC'},
  {key: 'AMP', text: 'Synereo', value: 'AMP'},
  {key: 'SYS', text: 'Syscoin', value: 'SYS'},
  {key: 'TRX', text: 'TRON', value: 'TRX'},
  {key: 'TAAS', text: 'TaaS', value: 'TAAS'},
  {key: 'TEL', text: 'Telcoin', value: 'TEL'},
  {key: 'PAY', text: 'TenX', value: 'PAY'},
  {key: 'USDT', text: 'Tether', value: 'USDT'},
  {key: 'THETA', text: 'Theta Token', value: 'THETA'},
  {key: 'TNT', text: 'Tierion', value: 'TNT'},
  {key: 'TNB', text: 'Time New Bank', value: 'TNB'},
  {key: 'TKN', text: 'TokenCard', value: 'TKN'},
  {key: 'TIO', text: 'Trade Token', value: 'TIO'},
  {key: 'TRIG', text: 'Triggers', value: 'TRIG'},
  {key: 'TNC', text: 'Trinity Network Credit', value: 'TNC'},
  {key: 'UTK', text: 'UTRUST', value: 'UTK'},
  {key: 'UBQ', text: 'Ubiq', value: 'UBQ'},
  {key: 'UKG', text: 'Unikoin Gold', value: 'UKG'},
  {key: 'UNO', text: 'Unobtanium', value: 'UNO'},
  {key: 'VIBE', text: 'VIBE', value: 'VIBE'},
  {key: 'VEN', text: 'VeChain', value: 'VEN'},
  {key: 'XVG', text: 'Verge', value: 'XVG'},
  {key: 'VRC', text: 'VeriCoin', value: 'VRC'},
  {key: 'VERI', text: 'Veritaseum', value: 'VERI'},
  {key: 'VTC', text: 'Vertcoin', value: 'VTC'},
  {key: 'VIA', text: 'Viacoin', value: 'VIA'},
  {key: 'VIB', text: 'Viberate', value: 'VIB'},
  {key: 'VOX', text: 'Voxels', value: 'VOX'},
  {key: 'WAX', text: 'WAX', value: 'WAX'},
  {key: 'WABI', text: 'WaBi', value: 'WABI'},
  {key: 'WGR', text: 'Wagerr', value: 'WGR'},
  {key: 'WTC', text: 'Walton', value: 'WTC'},
  {key: 'WAVES', text: 'Waves', value: 'WAVES'},
  {key: 'TRST', text: 'WeTrust', value: 'TRST'},
  {key: 'XWC', text: 'WhiteCoin', value: 'XWC'},
  {key: 'WINGS', text: 'Wings', value: 'WINGS'},
  {key: 'WRC', text: 'Worldcore', value: 'WRC'},
  {key: 'XPA', text: 'XPlay', value: 'XPA'},
  {key: 'XBY', text: 'XTRABYTES', value: 'XBY'},
  {key: 'YOYOW', text: 'YOYOW', value: 'YOYOW'},
  {key: 'ZCL', text: 'ZClassic', value: 'ZCL'},
  {key: 'XZC', text: 'ZCoin', value: 'XZC'},
  {key: 'ZEC', text: 'Zcash', value: 'ZEC'},
  {key: 'ZEN', text: 'ZenCash', value: 'ZEN'},
  {key: 'ZSC', text: 'Zeusshield', value: 'ZSC'},
  {key: 'ZIL', text: 'Zilliqa', value: 'ZIL'},
]

export default coinOptions;
